"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { ArrowUpRight, Menu } from "lucide-react";
import { useState, Suspense } from "react";
import { Brand } from "../brand";
import { Preferences } from "../preferences";
import { Button } from "../ui/button";
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogTrigger } from "../ui/dialog";
import { dictionary, type Locale } from "@/lib/i18n";
export function Header({ locale }: { locale: Locale }) { const text = dictionary(locale); const pathname = usePathname(); const [open, setOpen] = useState(false); const links = ["features", "pricing", "about", "faq"] as const; return <header className="sticky top-0 z-40 border-b border-border/75 bg-background/95 backdrop-blur-md"><div className="container-page flex h-21 items-center justify-between gap-4"><Brand locale={locale} /><nav aria-label={text.nav.menu} className="hidden items-center gap-7 lg:flex"><Link className="text-xs font-semibold text-muted-foreground hover:text-foreground" href={`/${locale}`}>{text.nav.home}</Link>{links.map(key => <Link key={key} href={`/${locale}/${key}`} aria-current={pathname === `/${locale}/${key}` ? "page" : undefined} className="text-xs font-semibold text-muted-foreground transition-colors hover:text-foreground aria-[current=page]:text-accent">{text.nav[key]}</Link>)}</nav><div className="hidden items-center gap-3 lg:flex"><Suspense><Preferences locale={locale} /></Suspense><span className="mx-1 h-5 border-l" /><Link href={`/${locale}/login`} className="text-xs font-semibold">{text.nav.login}</Link><Button size="sm" asChild><Link href={`/${locale}/register`}>{text.nav.start}<ArrowUpRight /></Link></Button></div><div className="flex items-center gap-1 lg:hidden"><Suspense><Preferences locale={locale} /></Suspense><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button aria-label={text.nav.menu} size="icon" variant="ghost"><Menu /></Button></DialogTrigger><DialogContent closeLabel={text.nav.close}><DialogTitle className="mb-1 text-xl font-semibold">{text.nav.menu}</DialogTitle><DialogDescription className="mb-5 text-sm text-muted-foreground">{text.tagline}</DialogDescription><nav className="grid gap-2">{["home", ...links].map(key => <Link key={key} onClick={() => setOpen(false)} className="rounded-lg p-3 hover:bg-muted" href={`/${locale}${key === "home" ? "" : `/${key}`}`}>{text.nav[key as keyof typeof text.nav]}</Link>)}<Button variant="outline" asChild><Link href={`/${locale}/login`} onClick={() => setOpen(false)}>{text.nav.login}</Link></Button><Button asChild><Link href={`/${locale}/register`} onClick={() => setOpen(false)}>{text.nav.start}<ArrowUpRight /></Link></Button></nav></DialogContent></Dialog></div></div></header>; }
